# vi:et:ts=2 sw=2 sts=2
image: pidgin/builder-debian:stretch
pipelines:
  default:
    - step:
        script:
          - set -ex
          - sudo apt-get install libpurple-dev libjson-glib-dev libglib2.0-dev libprotobuf-c-dev protobuf-c-compiler mercurial make;
          - hg clone https://bitbucket.org/EionRobb/purple-hangouts/ && cd purple-hangouts;
          - make && sudo make install